/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.test.service.thriftdatatype;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class thrift_datatypeConstants {

  public static final java.lang.String VERSION = "1.0.1";

}
