@startuml

package "客户端" {
    [TServiceClient] as C
    () "TProtocol" as C.TPt
    interface "TTransport" as C.TT

    C.TT -up.> C.TPt
    C.TPt -up.> C : 12.返回调用结果
    C -down-> C.TPt : 1.调用接口方法
    C.TPt -down-> C.TT
    Network .left.> C.TT
    C.TT -right-> Network
    note right of C.TPt: 2.将函数名和参数\n按照协议进行封装
    note bottom of C.TT
        3.将协议层封装的结果进行处理后
        通过网络传输给Thrift服务器
        e.g. TFramedTransport将协议层
        封装的数据封装成帧进行传输:
        | 4字节的帧长 | 帧内容 |
    end note
    note left of C.TT : 10.接收调用结果数据进行逆向处理
    note left of C.TPt : 11.将数据按照协议进行解封装\n并交付客户端
}
cloud Network {
}
package "服务端" {
    component TServer #fefece {
        interface TProcessor as S.TPc
    }
    interface "TTransport" as S.TT
    () "TProtocol" as S.TPt

    S.TT .right.> Network
    Network -left-> S.TT
    S.TT -up-> S.TPt
    S.TPt -up-> S.TPc
    S.TPc -> S.TPc : 7.调用函数
    S.TPc -down.> S.TPt
    S.TPt -down.> S.TT
    note bottom of S.TT : 4.接收调用请求数据进行逆向处理
    note left of S.TPt : 5.将封装的调用的函数名和参数\n按照协议解封装
    note left of S.TPc : 6.根据函数名找到对应的函数对象
    note right of S.TPt : 8.将函数调用结果按协议进行封装
    note right of S.TT : 9.对协议层封装结果进行处理(如封装成帧)\n然后进行传输
}
@enduml